[package]
name = "tf2_demostats"
description = "Summarize detailed match stats"
version = "0.1.1"
authors = ["Leigh MacDonald <leigh.macdonald@gmail.com>"]
license = "MIT"
repository = "https://github.com/leighmacdonald/tf2_demostats"
edition = "2021"

[lib]
name = "tf2_demostats"
path = "src/lib.rs"

[[bin]]
name = "demostats"
path = "src/bin/main.rs"

[dependencies]
actix-web = "4.9"
actix-multipart = "0.7.2"
env_logger = "0.11.3"
log = "0.4.21"
tf-demo-parser = "0.5.1"
fnv = "1.0.7"
serde = { version = "1.0.197", features = ["derive"] }
mime = "0.3.17"
